//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteOfFineArts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Remakes = new HashSet<Remake>();
        }
    
        public long ID { get; set; }
        public int EventID { get; set; }
        public int StudentID { get; set; }
        public string ImageSource { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Reward { get; set; }
        public Nullable<bool> ForSale { get; set; }
        public Nullable<long> Price { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remake> Remakes { get; set; }
    }
}
