//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteOfFineArts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remake
    {
        public long ID { get; set; }
        public long ProductID { get; set; }
        public int StaffID { get; set; }
        public double MarkAssigned { get; set; }
        public string Content { get; set; }
    
        public virtual AttendedStaff AttendedStaff { get; set; }
        public virtual Product Product { get; set; }
    }
}
